import PrimesRestrictedDigits.ExceptionalMinorArcs.SparseLowHeightPlanes

/-!
# Pairs generated by lines with many bounded integer points

This is the exact finite carrier in `MAYNARD-PRD-PUBLISHED`, Proposition 13.4, p. 196.
-/

namespace PrimesRestrictedDigits

/-- The integer points on a source line satisfying the norm and linear-form
bounds in Proposition 13.4. -/
noncomputable def lineGeneratingIntegerPoints {X : Nat}
    (a1 a2 : Fin X)
    (line : Submodule Real (EuclideanSpace Real (Fin 3)))
    (delta N : Real) : Finset (Fin 3 -> Int) := by
  classical
  exact (Fintype.piFinset fun _ : Fin 3 => lineCoefficientBox N).filter fun z =>
    And (intVectorToEuclidean z ∈ line)
      (And (‖intVectorToEuclidean z‖ <= N)
        (|((intVectorDot z (lineCoefficientVector a1 a2) : Int) : Real)| <=
          delta * (X : Real)))

/-- For nonnegative radius, the finite box enumeration gives exactly the
source's norm-bounded integer points. -/
@[simp]
theorem mem_lineGeneratingIntegerPoints {X : Nat}
    {a1 a2 : Fin X}
    {line : Submodule Real (EuclideanSpace Real (Fin 3))}
    {delta N : Real} (hN : 0 <= N) {z : Fin 3 -> Int} :
    z ∈ lineGeneratingIntegerPoints a1 a2 line delta N <->
      And (intVectorToEuclidean z ∈ line)
        (And (‖intVectorToEuclidean z‖ <= N)
          (|((intVectorDot z (lineCoefficientVector a1 a2) : Int) : Real)| <=
            delta * (X : Real))) := by
  classical
  rw [lineGeneratingIntegerPoints, Finset.mem_filter]
  constructor
  · exact fun hz => hz.2
  · intro hz
    refine ⟨Fintype.mem_piFinset.mpr ?_, hz⟩
    intro i
    rw [mem_lineCoefficientBox_iff hN]
    have hi := PiLp.norm_apply_le (intVectorToEuclidean z) i
    have hiAbs : |((z i : Int) : Real)| <= ‖intVectorToEuclidean z‖ := by
      simpa [Real.norm_eq_abs] using hi
    exact hiAbs.trans hz.2.1

/-- A source pair admits a real line through zero with the required number of
bounded integer points. A finrank-one submodule is exactly such a line. -/
def IsLineGeneratingPair {X : Nat}
    (delta N K : Real) (a1 a2 : Fin X) : Prop :=
  exists line : Submodule Real (EuclideanSpace Real (Fin 3)),
    And (Module.finrank Real line = 1)
      (delta * N ^ 2 * K <=
        ((lineGeneratingIntegerPoints a1 a2 line delta N).card : Real))

/-- Ordered line-generating pairs whose two coordinates lie in `C`. -/
noncomputable def lineGeneratingPairs {X : Nat}
    (C : Finset (Fin X)) (delta N K : Real) :
    Finset (Prod (Fin X) (Fin X)) := by
  classical
  exact (C.product C).filter fun pair =>
    IsLineGeneratingPair delta N K pair.1 pair.2

@[simp]
theorem mem_lineGeneratingPairs {X : Nat}
    {C : Finset (Fin X)} {delta N K : Real} {a1 a2 : Fin X} :
    (a1, a2) ∈ lineGeneratingPairs C delta N K <->
      And (a1 ∈ C) (And (a2 ∈ C)
        (IsLineGeneratingPair delta N K a1 a2)) := by
  classical
  simp [lineGeneratingPairs, and_assoc]

/-- Filtering the ordered square never increases its cardinality. -/
theorem card_lineGeneratingPairs_le_sq {X : Nat}
    (C : Finset (Fin X)) (delta N K : Real) :
    (lineGeneratingPairs C delta N K).card <= C.card ^ 2 := by
  classical
  calc
    (lineGeneratingPairs C delta N K).card <= (C.product C).card := by
      exact Finset.card_filter_le _ _
    _ = C.card * C.card := Finset.card_product C C
    _ = C.card ^ 2 := by ring

/--
turns one source line witness into a nontrivial integral plane relation with coordinate height
`4*X/(N^2*K)`.
-/
theorem isLowHeightPlanePair_of_isLineGeneratingPair
    {X : Nat} (hX : 0 < X) (a1 a2 : Fin X)
    (delta N K : Real)
    (hdelta : 0 < delta) (hN : 0 < N) (hK : 0 < K)
    (hscale : 2 <= delta * N ^ 2 * K)
    (hwidth : N <= delta * (X : Real))
    (hpair : IsLineGeneratingPair delta N K a1 a2) :
    IsLowHeightPlanePair
      (4 * (X : Real) / (N ^ 2 * K)) a1 a2 := by
  obtain ⟨line, hline, hcount⟩ := hpair
  let S := lineGeneratingIntegerPoints a1 a2 line delta N
  have hmem : ∀ z ∈ S, intVectorToEuclidean z ∈ line := by
    intro z hz
    exact ((mem_lineGeneratingIntegerPoints hN.le).mp hz).1
  have hnorm : ∀ z ∈ S, ‖intVectorToEuclidean z‖ <= N := by
    intro z hz
    exact ((mem_lineGeneratingIntegerPoints hN.le).mp hz).2.1
  have hdot : ∀ z ∈ S,
      |((intVectorDot z (lineCoefficientVector a1 a2) : Int) : Real)| <=
        delta * (X : Real) := by
    intro z hz
    exact ((mem_lineGeneratingIntegerPoints hN.le).mp hz).2.2
  obtain ⟨v, v4, hv, hrelation, hvBound, hv4Bound⟩ :=
    exists_lowHeightIntegerRelation_of_collinear hX a1 a2 line hline S
      1 delta N K (by norm_num) hdelta hN hK (by simpa [S] using hcount)
      (by simpa using hscale) hwidth hmem hnorm hdot
  refine ⟨v, v4, Or.inl hv, ?_, ?_, hrelation⟩
  · intro i
    simpa using hvBound i
  · simpa using hv4Bound

/--
Every source line-generating pair lies in the carrier at the height supplied.
-/
theorem lineGeneratingPairs_subset_lowHeightPlanePairs
    {X : Nat} (hX : 0 < X) (C : Finset (Fin X))
    (delta N K : Real)
    (hdelta : 0 < delta) (hN : 0 < N) (hK : 0 < K)
    (hscale : 2 <= delta * N ^ 2 * K)
    (hwidth : N <= delta * (X : Real)) :
    lineGeneratingPairs C delta N K ⊆
      lowHeightPlanePairs C (4 * (X : Real) / (N ^ 2 * K)) := by
  intro pair hpair
  have hp := mem_lineGeneratingPairs.mp hpair
  exact mem_lowHeightPlanePairs.mpr
    ⟨hp.1, hp.2.1,
      isLowHeightPlanePair_of_isLineGeneratingPair hX pair.1 pair.2
        delta N K hdelta hN hK hscale hwidth hp.2.2⟩

/--
If the height is below one, the source line-pair carrier is empty.
-/
theorem lineGeneratingPairs_eq_empty_of_height_lt_one
    {X : Nat} (hX : 0 < X) (C : Finset (Fin X))
    (delta N K : Real)
    (hdelta : 0 < delta) (hN : 0 < N) (hK : 0 < K)
    (hscale : 2 <= delta * N ^ 2 * K)
    (hwidth : N <= delta * (X : Real))
    (hheight : 4 * (X : Real) / (N ^ 2 * K) < 1) :
    lineGeneratingPairs C delta N K = Finset.empty := by
  apply Finset.eq_empty_iff_forall_notMem.mpr
  intro pair hpair
  have hlow := lineGeneratingPairs_subset_lowHeightPlanePairs
    hX C delta N K hdelta hN hK hscale hwidth hpair
  exact not_isLowHeightPlanePair_of_lt_one hheight pair.1 pair.2
    (mem_lowHeightPlanePairs.mp hlow).2.2

end PrimesRestrictedDigits
