import BoundedGaps.Maynard.ImprovedGPY.CongruenceCount

noncomputable section

/-!
# Squarefree S2 CRT moduli

Maynard2013v3, in the error part of `lmm:S2Expression1` (source line 363),
uses that the CRT moduli generated by supported divisor pairs are squarefree.
This file derives that property from the tuple support, cross-coordinate
coprimality, and squarefreeness of the pre-sieving modulus.
-/

namespace BoundedGaps.Maynard

open scoped BigOperators

theorem squarefree_divisorTupleLcm
    {H : Finset ℕ} {R W : ℕ} {d e : H → ℕ}
    (hd : IsMaynardDivisorTuple H R W d)
    (he : IsMaynardDivisorTuple H R W e) (h : H) :
    Squarefree (divisorTupleLcm H d e h) := by
  apply Nat.squarefree_of_factorization_le_one
  · exact Nat.lcm_ne_zero (hd.coordinate_squarefree h).ne_zero
      (he.coordinate_squarefree h).ne_zero
  · intro p
    change (Nat.lcm (d h) (e h)).factorization p ≤ 1
    rw [Nat.factorization_lcm (hd.coordinate_squarefree h).ne_zero
      (he.coordinate_squarefree h).ne_zero]
    exact sup_le ((hd.coordinate_squarefree h).natFactorization_le_one p)
      ((he.coordinate_squarefree h).natFactorization_le_one p)

theorem squarefree_divisorTupleLcmProduct
    {H : Finset ℕ} {R W : ℕ} {d e : H → ℕ}
    (hd : IsMaynardDivisorTuple H R W d)
    (he : IsMaynardDivisorTuple H R W e)
    (hcross : IsCrossCoordinateCoprime H d e) :
    Squarefree (∏ h : H, divisorTupleLcm H d e h) := by
  classical
  apply Finset.squarefree_prod_of_pairwise_isCoprime
  · intro a ha b hb hab
    apply Nat.coprime_iff_isRelPrime.mp
    have hdd : Nat.Coprime (d a) (d b) := hd.coordinates_coprime hab
    have hee : Nat.Coprime (e a) (e b) := he.coordinates_coprime hab
    obtain ⟨hde, hed⟩ := hcross hab
    exact coprime_lcm_lcm_of_four hdd hde hed hee
  · intro h hh
    exact squarefree_divisorTupleLcm hd he h

theorem squarefree_divisorPairModulus
    {H : Finset ℕ} {R W : ℕ} {d e : H → ℕ}
    (hW : Squarefree W)
    (hd : IsMaynardDivisorTuple H R W d)
    (he : IsMaynardDivisorTuple H R W e)
    (hcross : IsCrossCoordinateCoprime H d e) :
    Squarefree (divisorPairModulus H W d e) := by
  unfold divisorPairModulus
  apply (Nat.squarefree_mul ?_).mpr
  · exact ⟨hW, squarefree_divisorTupleLcmProduct hd he hcross⟩
  · apply Nat.Coprime.prod_right
    intro h hh
    have hWd : Nat.Coprime W (d h) := (hd.coordinate_coprime_W h).symm
    have hWe : Nat.Coprime W (e h) := (he.coordinate_coprime_W h).symm
    exact Nat.Coprime.of_dvd_right (Nat.lcm_dvd_mul (d h) (e h))
      (hWd.mul_right hWe)

end BoundedGaps.Maynard
