import BoundedGaps.Maynard.ImprovedGPY.S2Distribution

noncomputable section

/-!
# Supported CRT modulus sets for S2

Maynard2013v3, in the proof of `lmm:S2Expression1` (source lines 395--410),
applies prime distribution estimates to the CRT moduli generated by supported
divisor-tuple pairs. This file packages that finite modulus image and its
uniform cutoff inclusion.
-/

namespace BoundedGaps.Maynard

local instance (p : Prop) : Decidable p := Classical.propDecidable p

def supportedDivisorPairModuli
    (H : Finset ℕ) (D : Finset (H → ℕ)) (W : ℕ) : Finset ℕ :=
  (D ×ˢ D).image fun de => divisorPairModulus H W de.1 de.2

theorem divisorPairModulus_mem_supportedDivisorPairModuli
    {H : Finset ℕ} {D : Finset (H → ℕ)} {W : ℕ}
    {d e : H → ℕ} (hd : d ∈ D) (he : e ∈ D) :
    divisorPairModulus H W d e ∈ supportedDivisorPairModuli H D W := by
  apply Finset.mem_image.mpr
  exact ⟨(d, e), Finset.mem_product.mpr ⟨hd, he⟩, rfl⟩

theorem supportedDivisorPairModuli_subset_cutoff
    {H : Finset ℕ} {D : Finset (H → ℕ)} {θ : ℝ} {x R W : ℕ}
    (hW : 0 < W)
    (hD : ∀ d ∈ D, IsMaynardDivisorTuple H R W d)
    (hcut : W * R * R ≤ modulusCutoff θ x) :
    supportedDivisorPairModuli H D W ⊆
      Finset.Icc 1 (modulusCutoff θ x) := by
  intro q hq
  obtain ⟨de, hde, rfl⟩ := Finset.mem_image.mp hq
  obtain ⟨hd, he⟩ := Finset.mem_product.mp hde
  exact divisorPairModulus_mem_Icc_of_W_mul_R_sq hW
    (hD de.1 hd) (hD de.2 he) hcut

theorem supportedDivisorPairModuli_pos
    {H : Finset ℕ} {D : Finset (H → ℕ)} {R W : ℕ}
    (hW : 0 < W)
    (hD : ∀ d ∈ D, IsMaynardDivisorTuple H R W d) :
    ∀ q ∈ supportedDivisorPairModuli H D W, 0 < q := by
  intro q hq
  obtain ⟨de, hde, rfl⟩ := Finset.mem_image.mp hq
  obtain ⟨hd, he⟩ := Finset.mem_product.mp hde
  exact divisorPairModulus_pos hW (hD de.1 hd) (hD de.2 he)

end BoundedGaps.Maynard
