import Waring.Analytic.WeilWeights
import Mathlib.FieldTheory.Finite.Trace
import Mathlib.FieldTheory.SeparableDegree

/-!
# Formal-root weights and finite-field traces

This file identifies the coefficient-defined formal-root phase of a minimal
polynomial with the field trace of the corresponding point phase.  It then
records the tower form needed when that root is viewed in a larger finite
extension.
-/

namespace Waring.Analytic

open IntermediateField Polynomial

namespace Weil

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- For a separable algebraic element, the formal-root phase of its minimal
polynomial is the trace of the point phase from the simple extension it
generates. -/
theorem formalRootPhase_minpoly_eq_trace_adjoin
    (b : Fin 5 → K) (x : L) (hx : IsIntegral K x) (hsep : IsSeparable K x) :
    formalRootPhase b (minpoly K x) =
      Algebra.trace K K⟮x⟯
        (pointPhase ((algebraMap K K⟮x⟯) ∘ b)
          (IntermediateField.AdjoinSimple.gen K x)) := by
  classical
  let E := AlgebraicClosure L
  letI : FiniteDimensional K K⟮x⟯ := IntermediateField.adjoin.finiteDimensional hx
  letI : Algebra.IsSeparable K K⟮x⟯ :=
    (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable K L).2 hsep
  apply (algebraMap K E).injective
  rw [formalRootPhase_eq_sum_roots_map (algebraMap K E) b
      (minpoly.monic hx) (IsAlgClosed.splits _),
    trace_eq_sum_embeddings E]
  have hemb :
      (∑ σ : K⟮x⟯ →ₐ[K] E,
        σ (pointPhase ((algebraMap K K⟮x⟯) ∘ b)
          (IntermediateField.AdjoinSimple.gen K x))) =
        ∑ y : {y // y ∈ (minpoly K x).aroots E},
          pointPhase ((algebraMap K E) ∘ b) y := by
    let e := IntermediateField.algHomAdjoinIntegralEquiv K (K := E) hx
    apply Fintype.sum_equiv e
    intro σ
    have heval : (e σ : E) =
        σ (IntermediateField.AdjoinSimple.gen K x) := by
      symm
      simpa [e] using
        IntermediateField.algHomAdjoinIntegralEquiv_symm_apply_gen
          K hx (e σ)
    rw [show σ (pointPhase ((algebraMap K K⟮x⟯) ∘ b)
        (IntermediateField.AdjoinSimple.gen K x)) =
          pointPhase (σ.toRingHom ∘ ((algebraMap K K⟮x⟯) ∘ b))
            (σ (IntermediateField.AdjoinSimple.gen K x)) from
      pointPhase_map σ.toRingHom _ _]
    rw [heval]
    congr 1
    funext i
    exact σ.commutes (b i)
  rw [hemb]
  rw [Finset.sum_mem_multiset, Finset.sum_eq_multiset_sum,
    Multiset.toFinset_val,
    Multiset.dedup_eq_self.mpr
      (nodup_roots ((Polynomial.separable_map _).mpr hsep))]
  intro y
  rfl

/-- The formal-root weight of a minimal polynomial is the additive character
of the trace from the simple extension generated by the root. -/
theorem formalRootWeight_minpoly_eq_character_trace_adjoin
    (character : AddChar K Complex) (b : Fin 5 → K) (x : L)
    (hx : IsIntegral K x) (hsep : IsSeparable K x) :
    formalRootWeight character b (minpoly K x) =
      character
        (Algebra.trace K K⟮x⟯
          (pointPhase ((algebraMap K K⟮x⟯) ∘ b)
            (IntermediateField.AdjoinSimple.gen K x))) := by
  rw [formalRootWeight, formalRootPhase_minpoly_eq_trace_adjoin b x hx hsep]

/-- If a monic irreducible polynomial vanishes at a separable root, its
formal-root weight is the trace character of the point phase at that root. -/
theorem formalRootWeight_eq_character_trace_adjoin_of_root
    (character : AddChar K Complex) (b : Fin 5 → K) (P : K[X])
    (hPirr : Irreducible P) (hPmonic : P.Monic) (x : L)
    (hroot : Polynomial.aeval x P = 0) (hsep : IsSeparable K x) :
    formalRootWeight character b P =
      character
        (Algebra.trace K K⟮x⟯
          (pointPhase ((algebraMap K K⟮x⟯) ∘ b)
            (IntermediateField.AdjoinSimple.gen K x))) := by
  rw [minpoly.eq_of_irreducible_of_monic hPirr hroot hPmonic]
  exact formalRootWeight_minpoly_eq_character_trace_adjoin
    character b x hsep.isIntegral hsep

/-- In a finite ambient extension, the trace character of a point phase is the
formal-root weight of the point's minimal polynomial raised to the relative
degree over the simple subextension. -/
theorem character_trace_pointPhase_eq_formalRootWeight_pow
    [FiniteDimensional K L] (character : AddChar K Complex)
    (b : Fin 5 → K) (x : L) (hsep : IsSeparable K x) :
    character
        (Algebra.trace K L
          (pointPhase ((algebraMap K L) ∘ b) x)) =
      formalRootWeight character b (minpoly K x) ^
        Module.finrank K⟮x⟯ L := by
  let y : K⟮x⟯ :=
    pointPhase ((algebraMap K K⟮x⟯) ∘ b)
      (IntermediateField.AdjoinSimple.gen K x)
  have hpoint : algebraMap K⟮x⟯ L y =
      pointPhase ((algebraMap K L) ∘ b) x := by
    dsimp only [y]
    rw [pointPhase_map (algebraMap K⟮x⟯ L)]
    congr 1
  have htrace :
      Algebra.trace K L (algebraMap K⟮x⟯ L y) =
        Module.finrank K⟮x⟯ L • Algebra.trace K K⟮x⟯ y := by
    calc
      Algebra.trace K L (algebraMap K⟮x⟯ L y) =
          Algebra.trace K K⟮x⟯
            (Algebra.trace K⟮x⟯ L (algebraMap K⟮x⟯ L y)) := by
        rw [Algebra.trace_trace]
      _ = Algebra.trace K K⟮x⟯ (Module.finrank K⟮x⟯ L • y) := by
        rw [Algebra.trace_algebraMap]
      _ = Module.finrank K⟮x⟯ L • Algebra.trace K K⟮x⟯ y := by
        exact map_nsmul (Algebra.trace K K⟮x⟯) _ _
  rw [← hpoint, htrace, AddChar.map_nsmul_eq_pow,
    ← formalRootWeight_minpoly_eq_character_trace_adjoin
      character b x hsep.isIntegral hsep]

/-- Quotient form of `character_trace_pointPhase_eq_formalRootWeight_pow`,
with the exponent written as the ambient degree divided by the degree of the
minimal polynomial. -/
theorem character_trace_pointPhase_eq_formalRootWeight_pow_div_natDegree
    [FiniteDimensional K L] (character : AddChar K Complex)
    (b : Fin 5 → K) (x : L) (hsep : IsSeparable K x) :
    character
        (Algebra.trace K L
          (pointPhase ((algebraMap K L) ∘ b) x)) =
      formalRootWeight character b (minpoly K x) ^
        (Module.finrank K L / (minpoly K x).natDegree) := by
  have hrelative :
      Module.finrank K⟮x⟯ L =
        Module.finrank K L / (minpoly K x).natDegree := by
    rw [← IntermediateField.adjoin.finrank hsep.isIntegral,
      ← Module.finrank_mul_finrank K K⟮x⟯ L,
      Nat.mul_div_cancel_left _ Module.finrank_pos]
  rw [← hrelative]
  exact character_trace_pointPhase_eq_formalRootWeight_pow
    character b x hsep

/-- Root-polynomial form of the ambient trace identity, with the exponent
written as the ambient degree divided by the irreducible polynomial's degree. -/
theorem character_trace_pointPhase_eq_formalRootWeight_pow_div_natDegree_of_root
    [FiniteDimensional K L] (character : AddChar K Complex)
    (b : Fin 5 → K) (P : K[X]) (hPirr : Irreducible P)
    (hPmonic : P.Monic) (x : L) (hroot : Polynomial.aeval x P = 0)
    (hsep : IsSeparable K x) :
    character
        (Algebra.trace K L
          (pointPhase ((algebraMap K L) ∘ b) x)) =
      formalRootWeight character b P ^
        (Module.finrank K L / P.natDegree) := by
  rw [minpoly.eq_of_irreducible_of_monic hPirr hroot hPmonic]
  exact character_trace_pointPhase_eq_formalRootWeight_pow_div_natDegree
    character b x hsep

/-- Over finite fields, separability and finite-dimensionality are automatic,
so the root-polynomial ambient trace identity needs no extra hypotheses. -/
theorem character_trace_pointPhase_eq_formalRootWeight_pow_div_natDegree_of_root_finite
    [Finite K] [Finite L] (character : AddChar K Complex)
    (b : Fin 5 → K) (P : K[X]) (hPirr : Irreducible P)
    (hPmonic : P.Monic) (x : L) (hroot : Polynomial.aeval x P = 0) :
    character
        (Algebra.trace K L
          (pointPhase ((algebraMap K L) ∘ b) x)) =
      formalRootWeight character b P ^
        (Module.finrank K L / P.natDegree) :=
  character_trace_pointPhase_eq_formalRootWeight_pow_div_natDegree_of_root
    character b P hPirr hPmonic x hroot
      (Algebra.IsSeparable.isSeparable K x)

end Weil

end Waring.Analytic
