import BoundedGaps.Maynard.MaynardYDivisorSum
import Mathlib.Algebra.GCDMonoid.Finset

noncomputable section

/-!
# Lower tuples generated by common and cross divisors

Finite lcm gives the exact lower tuple before Maynard's starred coprimality
restrictions are imposed.
-/

namespace BoundedGaps.Maynard

open scoped ArithmeticFunction.Moebius BigOperators
local instance lowerTuplesDecidable (p : Prop) : Decidable p :=
  Classical.propDecidable p

def outgoingCrossLcm
    (H : Finset ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ)
    (h : H) : ℕ :=
  ((offDiagonalPairs H).attach.filter (fun x => x.1.1 = h)).lcm
    (fun x => s x.1 x.2)

def incomingCrossLcm
    (H : Finset ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ)
    (h : H) : ℕ :=
  ((offDiagonalPairs H).attach.filter (fun x => x.1.2 = h)).lcm
    (fun x => s x.1 x.2)

def leftCrossLowerTuple
    (H : Finset ℕ) (u : H → ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ) : H → ℕ :=
  fun h => Nat.lcm (u h) (outgoingCrossLcm H s h)

def rightCrossLowerTuple
    (H : Finset ℕ) (u : H → ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ) : H → ℕ :=
  fun h => Nat.lcm (u h) (incomingCrossLcm H s h)

theorem outgoingCrossLcm_pos
    {H : Finset ℕ} {R : ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hs : s ∈ crossMoebiusTupleBox H R) (h : H) :
    0 < outgoingCrossLcm H s h := by
  apply Nat.pos_of_ne_zero
  rw [outgoingCrossLcm, ne_eq, Finset.lcm_eq_zero_iff]
  push Not
  intro x hx
  have hsMem := (Finset.mem_pi.mp hs) x.1 x.2
  exact Nat.ne_of_gt (zero_lt_one.trans_le (Finset.mem_Icc.mp hsMem).1)

theorem incomingCrossLcm_pos
    {H : Finset ℕ} {R : ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hs : s ∈ crossMoebiusTupleBox H R) (h : H) :
    0 < incomingCrossLcm H s h := by
  apply Nat.pos_of_ne_zero
  rw [incomingCrossLcm, ne_eq, Finset.lcm_eq_zero_iff]
  push Not
  intro x hx
  have hsMem := (Finset.mem_pi.mp hs) x.1 x.2
  exact Nat.ne_of_gt (zero_lt_one.trans_le (Finset.mem_Icc.mp hsMem).1)

theorem leftCrossLowerTuple_pos
    {H : Finset ℕ} {R : ℕ} {u : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hu : u ∈ maynardDivisorTupleBox H R)
    (hs : s ∈ crossMoebiusTupleBox H R) (h : H) :
    0 < leftCrossLowerTuple H u s h := by
  apply Nat.lcm_pos
  · exact (mem_maynardDivisorTupleBox_iff.mp hu h).1
  · exact outgoingCrossLcm_pos hs h

theorem rightCrossLowerTuple_pos
    {H : Finset ℕ} {R : ℕ} {u : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hu : u ∈ maynardDivisorTupleBox H R)
    (hs : s ∈ crossMoebiusTupleBox H R) (h : H) :
    0 < rightCrossLowerTuple H u s h := by
  apply Nat.lcm_pos
  · exact (mem_maynardDivisorTupleBox_iff.mp hu h).1
  · exact incomingCrossLcm_pos hs h

theorem leftCrossLowerTuple_dvd_iff
    {H : Finset ℕ}
    {u d : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ} :
    (∀ h : H, leftCrossLowerTuple H u s h ∣ d h) ↔
      LeftCrossDivides H u s d := by
  constructor
  · intro hdiv
    refine ⟨fun h => (Nat.lcm_dvd_iff.mp (hdiv h)).1, ?_⟩
    intro ab hab
    have hout := (Nat.lcm_dvd_iff.mp (hdiv ab.1)).2
    apply (Finset.lcm_dvd_iff.mp hout) ⟨ab, hab⟩
    exact Finset.mem_filter.mpr ⟨Finset.mem_attach _ _, rfl⟩
  · rintro ⟨hu, hs⟩ h
    apply Nat.lcm_dvd_iff.mpr
    refine ⟨hu h, Finset.lcm_dvd ?_⟩
    intro x hx
    have hxEq := (Finset.mem_filter.mp hx).2
    simpa [hxEq] using hs x.1 x.2

theorem rightCrossLowerTuple_dvd_iff
    {H : Finset ℕ}
    {u e : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ} :
    (∀ h : H, rightCrossLowerTuple H u s h ∣ e h) ↔
      RightCrossDivides H u s e := by
  constructor
  · intro hdiv
    refine ⟨fun h => (Nat.lcm_dvd_iff.mp (hdiv h)).1, ?_⟩
    intro ab hab
    have hin := (Nat.lcm_dvd_iff.mp (hdiv ab.2)).2
    apply (Finset.lcm_dvd_iff.mp hin) ⟨ab, hab⟩
    exact Finset.mem_filter.mpr ⟨Finset.mem_attach _ _, rfl⟩
  · rintro ⟨hu, hs⟩ h
    apply Nat.lcm_dvd_iff.mpr
    refine ⟨hu h, Finset.lcm_dvd ?_⟩
    intro x hx
    have hxEq := (Finset.mem_filter.mp hx).2
    simpa [hxEq] using hs x.1 x.2

def leftCrossYFactor
    (H : Finset ℕ) (y : (H → ℕ) → ℝ)
    (u : H → ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ) : ℝ :=
  (∏ h : H,
      (ArithmeticFunction.moebius (leftCrossLowerTuple H u s h) : ℝ)) *
    y (leftCrossLowerTuple H u s) /
      ∏ h : H, (Nat.totient (leftCrossLowerTuple H u s h) : ℝ)

def rightCrossYFactor
    (H : Finset ℕ) (y : (H → ℕ) → ℝ)
    (u : H → ℕ)
    (s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ) : ℝ :=
  (∏ h : H,
      (ArithmeticFunction.moebius (rightCrossLowerTuple H u s h) : ℝ)) *
    y (rightCrossLowerTuple H u s) /
      ∏ h : H, (Nat.totient (rightCrossLowerTuple H u s h) : ℝ)

theorem left_factoredCoefficientSum_eq_yFactor
    {H : Finset ℕ} {R W : ℕ} {y : (H → ℕ) → ℝ}
    (hy : IsSupportedMaynardY H R W y)
    {u : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hu : u ∈ maynardDivisorTupleBox H R)
    (hs : s ∈ crossMoebiusTupleBox H R) :
    (∑ d ∈ maynardDivisorTupleSupport H R W,
        if LeftCrossDivides H u s d then
          maynardCoefficientFromY H R W y d /
            (divisorTupleProduct H d : ℝ)
        else 0) = leftCrossYFactor H y u s := by
  unfold leftCrossYFactor
  calc
    (∑ d ∈ maynardDivisorTupleSupport H R W,
        if LeftCrossDivides H u s d then
          maynardCoefficientFromY H R W y d /
            (divisorTupleProduct H d : ℝ)
        else 0) =
        ∑ d ∈ maynardDivisorTupleSupport H R W,
          if ∀ h : H, leftCrossLowerTuple H u s h ∣ d h then
            maynardCoefficientFromY H R W y d /
              (divisorTupleProduct H d : ℝ)
          else 0 := by
      apply Finset.sum_congr rfl
      intro d hd
      by_cases hl : LeftCrossDivides H u s d
      · rw [if_pos hl, if_pos (leftCrossLowerTuple_dvd_iff.mpr hl)]
      · rw [if_neg hl, if_neg (fun h => hl
          (leftCrossLowerTuple_dvd_iff.mp h))]
    _ = _ := supportedDivisorSum_eq_mu_mul_y_div_totient hy
      (leftCrossLowerTuple_pos hu hs)

theorem right_factoredCoefficientSum_eq_yFactor
    {H : Finset ℕ} {R W : ℕ} {y : (H → ℕ) → ℝ}
    (hy : IsSupportedMaynardY H R W y)
    {u : H → ℕ}
    {s : ∀ ab : H × H, ab ∈ offDiagonalPairs H → ℕ}
    (hu : u ∈ maynardDivisorTupleBox H R)
    (hs : s ∈ crossMoebiusTupleBox H R) :
    (∑ e ∈ maynardDivisorTupleSupport H R W,
        if RightCrossDivides H u s e then
          maynardCoefficientFromY H R W y e /
            (divisorTupleProduct H e : ℝ)
        else 0) = rightCrossYFactor H y u s := by
  unfold rightCrossYFactor
  calc
    (∑ e ∈ maynardDivisorTupleSupport H R W,
        if RightCrossDivides H u s e then
          maynardCoefficientFromY H R W y e /
            (divisorTupleProduct H e : ℝ)
        else 0) =
        ∑ e ∈ maynardDivisorTupleSupport H R W,
          if ∀ h : H, rightCrossLowerTuple H u s h ∣ e h then
            maynardCoefficientFromY H R W y e /
              (divisorTupleProduct H e : ℝ)
          else 0 := by
      apply Finset.sum_congr rfl
      intro e he
      by_cases hr : RightCrossDivides H u s e
      · rw [if_pos hr, if_pos (rightCrossLowerTuple_dvd_iff.mpr hr)]
      · rw [if_neg hr, if_neg (fun h => hr
          (rightCrossLowerTuple_dvd_iff.mp h))]
    _ = _ := supportedDivisorSum_eq_mu_mul_y_div_totient hy
      (rightCrossLowerTuple_pos hu hs)

end BoundedGaps.Maynard
