import PrimesRestrictedDigits.BasicEstimates.IntegerVectors
import Mathlib.Geometry.Euclidean.Angle.Unoriented.CrossProduct
import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Tactic.FinCases

/-!
# Cross products for the lattice approximation

These are the algebraic three-dimensional identities used in the repaired
proof of `MAYNARD-PRD-PUBLISHED`, Lemma 14.1, pp. 200--201.
-/

noncomputable section

namespace PrimesRestrictedDigits

open Matrix Real WithLp

open scoped Matrix

private abbrev E := EuclideanSpace Real (Fin 3)

/-- The ordinary cross product, transported to Euclidean `L2` space. -/
def euclideanCross (u v : E) : E :=
  toLp 2 (ofLp u ⨯₃ ofLp v)

/-- The norm of a cross product is at most the product of the two norms. -/
theorem norm_euclideanCross_le (u v : E) :
    ‖euclideanCross u v‖ <= ‖u‖ * ‖v‖ := by
  rw [euclideanCross, InnerProductGeometry.norm_ofLp_crossProduct]
  exact mul_le_of_le_one_right
    (mul_nonneg (norm_nonneg u) (norm_nonneg v))
    (Real.sin_le_one _)

/-- A three-dimensional cross product is nonzero exactly for an independent
pair. -/
theorem euclideanCross_ne_zero_iff {u v : E} :
    euclideanCross u v ≠ 0 ↔ LinearIndependent Real ![u, v] := by
  rw [euclideanCross, ne_eq, WithLp.toLp_eq_zero]
  change (ofLp u ⨯₃ ofLp v ≠ 0) ↔ LinearIndependent Real ![u, v]
  rw [crossProduct_ne_zero_iff_linearIndependent]
  constructor
  · intro h
    have hm := h.map' (WithLp.linearEquiv 2 Real _).symm.toLinearMap (by simp)
    have heq :
        (WithLp.linearEquiv 2 Real _).symm.toLinearMap ∘ ![ofLp u, ofLp v] =
          ![u, v] := by
      funext i
      fin_cases i <;> rfl
    rw [heq] at hm
    exact hm
  · intro h
    have hm := h.map' (WithLp.linearEquiv 2 Real _).toLinearMap (by simp)
    have heq :
        (WithLp.linearEquiv 2 Real _).toLinearMap ∘ ![u, v] =
          ![ofLp u, ofLp v] := by
      funext i
      fin_cases i <;> rfl
    rw [heq] at hm
    exact hm

/-- Casting an integral cross product gives the Euclidean cross product. -/
theorem intVectorToEuclidean_cross (u v : Fin 3 -> Int) :
    intVectorToEuclidean (u ⨯₃ v) =
      euclideanCross (intVectorToEuclidean u) (intVectorToEuclidean v) := by
  ext i
  fin_cases i <;>
    simp [euclideanCross, cross_apply, sub_eq_add_neg]

/-- Orthogonal residual from the line spanned by `u cross v`. -/
def crossResidual (A u v : Fin 3 -> Real) : Fin 3 -> Real :=
  let c := u ⨯₃ v
  A - ((A ⬝ᵥ c) / (c ⬝ᵥ c)) • c

/-- The same residual in the dual basis generated by `u` and `v`. -/
def crossDualResidual (A u v : Fin 3 -> Real) : Fin 3 -> Real :=
  let c := u ⨯₃ v
  ((A ⬝ᵥ u) / (c ⬝ᵥ c)) • (v ⨯₃ c) +
    ((A ⬝ᵥ v) / (c ⬝ᵥ c)) • (c ⨯₃ u)

/-- Exact dual-basis identity for the residual from the cross-product axis. -/
theorem crossResidual_eq_crossDualResidual (A u v : Fin 3 -> Real)
    (hc : u ⨯₃ v ≠ 0) :
    crossResidual A u v = crossDualResidual A u v := by
  let c := u ⨯₃ v
  have hc0 : c ≠ 0 := by
    simpa [c] using hc
  have hc' : c ⬝ᵥ c ≠ 0 := by
    exact fun h => hc0 (dotProduct_self_eq_zero.mp h)
  have hfirst :
      c ⨯₃ (A ⨯₃ c) =
        (c ⬝ᵥ c) • A - (A ⬝ᵥ c) • c := by
    exact cross_cross_eq_smul_sub_smul' c A c
  have hsecond :
      A ⨯₃ c = (A ⬝ᵥ v) • u - (A ⬝ᵥ u) • v := by
    simpa only [c, dotProduct_comm u A] using
      cross_cross_eq_smul_sub_smul' A u v
  have hcross :
      c ⨯₃ (A ⨯₃ c) =
        (A ⬝ᵥ u) • (v ⨯₃ c) + (A ⬝ᵥ v) • (c ⨯₃ u) := by
    calc
      c ⨯₃ (A ⨯₃ c) =
          c ⨯₃ ((A ⬝ᵥ v) • u - (A ⬝ᵥ u) • v) := by rw [hsecond]
      _ = (A ⬝ᵥ v) • (c ⨯₃ u) - (A ⬝ᵥ u) • (c ⨯₃ v) := by
        rw [map_sub, map_smul, map_smul]
      _ = (A ⬝ᵥ u) • (v ⨯₃ c) + (A ⬝ᵥ v) • (c ⨯₃ u) := by
        rw [← cross_anticomm c v, smul_neg, sub_eq_add_neg, add_comm]
  have hnum :
      (c ⬝ᵥ c) • A - (A ⬝ᵥ c) • c =
        (A ⬝ᵥ u) • (v ⨯₃ c) + (A ⬝ᵥ v) • (c ⨯₃ u) :=
    hfirst.symm.trans hcross
  change A - ((A ⬝ᵥ c) / (c ⬝ᵥ c)) • c =
    ((A ⬝ᵥ u) / (c ⬝ᵥ c)) • (v ⨯₃ c) +
      ((A ⬝ᵥ v) / (c ⬝ᵥ c)) • (c ⨯₃ u)
  have hscaled := congrArg (fun x : Fin 3 -> Real => (c ⬝ᵥ c)⁻¹ • x) hnum
  simpa [smul_sub, smul_add, smul_smul, div_eq_mul_inv, hc',
    mul_comm, mul_left_comm, mul_assoc] using hscaled

end PrimesRestrictedDigits
