import PrimesRestrictedDigits.LatticeEstimates.IntegralLattice
import Mathlib.LinearAlgebra.Basis.Submodule

/-!
# Rank-two lattices generated by integer vectors

This packages two real-linearly independent integer triples as the exact
rank-two integral lattice that they span.
-/

noncomputable section

open scoped BigOperators

namespace PrimesRestrictedDigits

private abbrev E := EuclideanSpace Real (Fin 3)

private theorem int_linearCombination_embedding
    (z : Fin 2 -> Fin 3 -> Int) (a : Fin 2 -> Int) :
    intVectorToEuclidean (fun j => ∑ i, a i * z i j) =
      ∑ i, a i • intVectorToEuclidean (z i) := by
  ext j
  simp [ Int.cast_mul, zsmul_eq_mul]

/-- Two real-linearly independent integer vectors generate an exact rank-two
integral lattice. -/
def rankTwoIntegralLatticeOfIndependentIntegerVectors
    (z : Fin 2 -> Fin 3 -> Int)
    (hz : LinearIndependent Real fun i => intVectorToEuclidean (z i)) :
    RankTwoIntegralLattice := by
  let carrier : Submodule Int E :=
    Submodule.span Int (Set.range fun i => intVectorToEuclidean (z i))
  have hzInt : LinearIndependent Int fun i => intVectorToEuclidean (z i) :=
    hz.restrict_scalars (smul_left_injective Int one_ne_zero)
  let b : Module.Basis (Fin 2) Int carrier := Module.Basis.span hzInt
  refine
    { carrier := carrier
      integral := ?_
      basis := b }
  intro x
  let a : Fin 2 -> Int := b.equivFun x
  let w : Fin 3 -> Int := fun j => ∑ i, a i * z i j
  refine ⟨w, ?_⟩
  rw [show intVectorToEuclidean w =
      ∑ i, a i • intVectorToEuclidean (z i) by
    exact int_linearCombination_embedding z a]
  have hb (i : Fin 2) : ((b i : carrier) : E) =
      intVectorToEuclidean (z i) := by
    exact congrArg Subtype.val (Module.Basis.span_apply hzInt i)
  calc
    (∑ i, a i • intVectorToEuclidean (z i)) =
        ∑ i, a i • ((b i : carrier) : E) := by
      apply Finset.sum_congr rfl
      intro i _
      rw [hb]
    _ = ((∑ i, a i • b i : carrier) : E) := by
      simp only [Submodule.coe_sum, Submodule.coe_smul_of_tower]
    _ = (x : E) := by
      apply congrArg Subtype.val
      simp [a]

@[simp]
theorem rankTwoIntegralLatticeOfIndependentIntegerVectors_carrier
    (z : Fin 2 -> Fin 3 -> Int)
    (hz : LinearIndependent Real fun i => intVectorToEuclidean (z i)) :
    (rankTwoIntegralLatticeOfIndependentIntegerVectors z hz).carrier =
      Submodule.span Int (Set.range fun i => intVectorToEuclidean (z i)) :=
  by simp [rankTwoIntegralLatticeOfIndependentIntegerVectors]

theorem intVector_mem_rankTwoIntegralLatticeOfIndependentIntegerVectors
    (z : Fin 2 -> Fin 3 -> Int)
    (hz : LinearIndependent Real fun i => intVectorToEuclidean (z i))
    (a : Fin 2 -> Int) :
    intVectorToEuclidean (fun j => ∑ i, a i * z i j) ∈
      (rankTwoIntegralLatticeOfIndependentIntegerVectors z hz).carrier := by
  rw [rankTwoIntegralLatticeOfIndependentIntegerVectors_carrier,
    int_linearCombination_embedding]
  apply Submodule.sum_mem
  intro i _
  apply Submodule.smul_mem
  exact Submodule.subset_span (Set.mem_range_self i)

end PrimesRestrictedDigits
